### ISSUE TITLE
Are there any plans to exend this project for B660 motherboards?

### ISSUE THREAD

**Issue by darrynjordan** [t-8ch/linux-gigabyte-wmi-driver#13]
I have a Gigabyte B660 Gaming X DDR4 motherboard and would really appreciate support.
Is there any way that I could help make this happen?

**Comment by t-8ch** [comment]
1) Ignore the code in this repo
2) Boot a recent linux kernel.
3) Run "sudo modprobe gigabyte-wmi force_load=1"
4) Check dmesg and if a sensor device was created

**Comment by darrynjordan** [comment]
Nothing appears to update in `dmesg` when `sudo modprobe gigabyte-wmi force_load=1` is run.

Using 5.15.0-25-generic x86_64.

```
lsmod | grep gig:
gigabyte_wmi           20480  0
wmi                    32768  2 gigabyte_wmi,wmi_bmof
```

**Comment by darrynjordan** [comment]
Oh great! If I remove and then add the module it works i.e.
```
sudo modprobe -r gigabyte_wmi
sudo modprobe gigabyte-wmi force_load=1
```
I get `gigabyte-wmi DEADBEEF-2001-0000-00A0-C90629100000: Forcing load on unknown platform` in `dmesg`.

Then running `sensors`:
```
gigabyte_wmi-virtual-0
Adapter: Virtual device
temp1:        +33.0°C  
temp2:        +38.0°C  
temp3:        +26.0°C  
temp4:        +30.0°C  
temp5:        +30.0°C  
temp6:        +30.0°C
```

**Comment by darrynjordan** [comment]
One last thing - is it possible to get the label associated with each temperature? For instance, which one is the VRM?

**Comment by t-8ch** [comment]
Nice!
It would be great if you could submit  a patch for the upstream kernel to natively include support for this device.

At the moment the driver itself does not know about the labels.
You can either configure this in `sensors`/`libsensor` or the driver could be adapted.
Somebody would have to create the mapping from index to name.

**Comment by darrynjordan** [comment]
Great, thank you very much @t-8ch. I will use this as a opportunity to submit my first patch to the upstream kernel!

As a side-note, I also managed to get the `it87` module working with `acpi_enforce_resources=lax` and `sudo modprobe it87 force_id=0x8628`.
Do you know if there is anyone planning to extend the `it87` module for newer versions of the chip?

**Comment by t-8ch** [comment]
As your patch has been accepted into the mainline kernel I'll close this ticket here. Good job!

Apparently there a lot of issues with the it87 module and the chips it handles. And there is no documentation to go by, so chances for any new features are very slim.
