### ISSUE TITLE
X570S Aero G Support

### ISSUE THREAD

**Issue by mikeyo** [t-8ch/linux-gigabyte-wmi-driver#14]
Tried sensors on this board but it doesnt want to show the wmi sensors :-(
Any idea on how I can get this to work?

[ 2976.851317] gigabyte-wmi DEADBEEF-2001-0000-00A0-C90629100000: Forcing load on unknown platform
[ 2976.852058] gigabyte-wmi DEADBEEF-2001-0000-00A0-C90629100000: No temperature sensors usable

----lsmod
gigabyte_wmi           20480  0

----check hwmon
/sys/class/wmi_bus/wmi_bus-PNP0C14:00/DEADBEEF-2001-0000-00A0-C90629100000# ls
expensive  guid  instance_count  modalias  object_id  power/  subsystem@  uevent

----- grep
/sys/class/dmi/id/bios_date:10/13/2021
/sys/class/dmi/id/bios_release:5.17
/sys/class/dmi/id/bios_vendor:American Megatrends International, LLC.
/sys/class/dmi/id/bios_version:F3d
/sys/class/dmi/id/board_asset_tag:Default string
/sys/class/dmi/id/board_name:X570S AERO G
/sys/class/dmi/id/board_serial:Default string
/sys/class/dmi/id/board_vendor:Gigabyte Technology Co., Ltd.
/sys/class/dmi/id/board_version:Default string
/sys/class/dmi/id/chassis_asset_tag:Default string
/sys/class/dmi/id/chassis_serial:Default string
/sys/class/dmi/id/chassis_type:3
/sys/class/dmi/id/chassis_vendor:Default string
/sys/class/dmi/id/chassis_version:Default string
/sys/class/dmi/id/modalias:dmi:bvnAmericanMegatrendsInternational,LLC.:bvrF3d:bd10/13/2021:br5.17:svnGigabyteTechnologyCo.,Ltd.:pnX570SAEROG:pvr-CF:rvnGigabyteTechnologyCo.,Ltd.:rnX570SAEROG:rvrDefaultstring:cvnDefaultstring:ct3:cvrDefaultstring:skuDefaultstring:
/sys/class/dmi/id/product_family:X570 MB
/sys/class/dmi/id/product_name:X570S AERO G
/sys/class/dmi/id/product_serial:Default string
/sys/class/dmi/id/product_sku:Default string
/sys/class/dmi/id/product_uuid:035e02d8-04d3-0529-b006-f10700080009
/sys/class/dmi/id/product_version:-CF
/sys/class/dmi/id/sys_vendor:Gigabyte Technology Co., Ltd.
/sys/class/dmi/id/uevent:MODALIAS=dmi:bvnAmericanMegatrendsInternational,LLC.:bvrF3d:bd10/13/2021:br5.17:svnGigabyteTechnologyCo.,Ltd.:pnX570SAEROG:pvr-CF:rvnGigabyteTechnologyCo.,Ltd.:rnX570SAEROG:rvrDefaultstring:cvnDefaultstring:ct3:cvrDefaultstring:skuDefaultstring:

**Comment by t-8ch** [comment]
If the WMI APIs are not there this driver can do nothing. Sorry.
