### ISSUE TITLE
X470-AORUS-ULTRA-GAMING

### ISSUE THREAD

**Issue by t-8ch** [t-8ch/linux-gigabyte-wmi-driver#2]
Split from https://github.com/t-8ch/linux-gigabyte-wmi-driver/issues/1#issuecomment-814724928

@muzena What happens when you remove force_id and load the it87 driver with `modprobe  it87 dyndbg`?
I want to know which chip is on this board.
The detected chip will be reported via `dmesg`.

Also could you post a dump of your acpitables?
(Generate with `acpidump`)

**Comment by muzena** [comment]
@t-8ch 
Is this ok?
[dmesg.txt](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6270793/dmesg.txt)
[acpidump.txt](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6270794/acpidump.txt)

**Comment by t-8ch** [comment]
Looks good.

This board seems to have two of the chips installed one at IT8686 (not sure, could also be a different chip) at 0x2E and one IT8733 at 0x4E. But the WMI interface does not expose the temperature opcode.

**Comment by t-8ch** [comment]
The low-level ACPI functionality is there. So if it's possible to directly call into that then it would work.
(And lots of other things)
Waiting on the kernel folks for clarification on that.
