### ISSUE TITLE
X570 AORUS PRO (REV 1.0) BIOS F32

### ISSUE THREAD

**Issue by andrew-mcmahon** [t-8ch/linux-gigabyte-wmi-driver#3]
Hello Thomas - saw the [news story](https://www.phoronix.com/scan.php?page=news_item&px=Gigabyte-WMI-Linux-Temperature) and the [patch](https://patchwork.kernel.org/project/platform-driver-x86/patch/20210405204810.339763-1-linux@weissschuh.net/) - thought I'd give it a go! :smile:  
Hope you've not opened up _Pandora's box_?  :wink: 
<hr>  
Thought I'd open a topic up directly for this motherboard; think it's another problematic one.  

Without Grub workaround:  
[sudo sensors](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6271034/sensors_without_workaround.txt)
[sudo sensors-detect](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6271041/sensors_detect_without_workaround.txt)
[sudo dmesg after modprobe it87](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6271047/dmesg_without_workaround.txt)
Trying to force the chip type without the workaround applied i.e:
```
sudo modprobe it87 force_id=0x8733
modprobe: ERROR: could not insert 'it87': Device or resource busy
```

With **acpi_enforce_resources=lax** added to Grub plus `sudo modprobe it87 force_id=0x8733`:
[sudo sensors](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6271070/sensors_with_workaround.txt)
[sudo sensors-detect](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6271084/sensors_detect_workaround.txt)  
[sudo dmesg after sudo modprobe it87 force_id=0x8733](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6271089/dmesg_with_workaround.txt)  
  
[acpidump.txt](https://github.com/t-8ch/linux-gigabyte-wmi-driver/files/6271101/acpidump.txt)  
  
Hope it's clear what's going on there; many thanks.

**Comment by t-8ch** [comment]
oh there is a news story, good to know :-)

Essentially this looks the same as #2

**Comment by t-8ch** [comment]
If you try the latest version of the module it should show "N/A" instead of 0 in the output of "sensors".
